services:
  front-end:
    container_name: front-end
    build: .
    image: front-end
    networks:
      - drivenpass-network
    ports:
      - 80:80
  
networks:
  drivenpass-network:
    name: drivenpass-network
    external: true